### ISSUE TITLE
How to use uploaded image?

### ISSUE THREAD

**Issue by shubhashis-k** [benglard/waffle#10]
In the readme section there is a code snippet - 

```
app.post('/', function(req, res)
   local img = req.form.file:toImage()
   local m = img:mean()
   res.send('Image mean: ' .. m)
end)
```

It is supposed to work with images. I can't get it to work. How should I send the image via the POST? I am using postman to send POST objects to the server. 

I can't understand what  this code (`req.form.file:toImage()`) means.

**Comment by benglard** [comment]
req.form stores the request form body. req.form.file represents an input field within the form named file. So if you were using command line curl, you could do a post request like this:
`curl --form "file=@image.jpeg" 127.0.0.1/` to send an image to the server named file. Or you could show a web page with an html form and an input field of the form type with html name="file". In either case (I've never used postman but I assume it would be the same), req.form.file will store the binary image data. Calling req.form.file:toImage will turn that data into a torch.FloatTensor in typical RGB DHW format so it can be used. Does that make sense?

**Comment by shubhashis-k** [comment]
Thanks @benglard . It makes sense
