### ISSUE TITLE
Thanks for the great library. Is these any support for HTTPS?

### ISSUE THREAD

**Issue by alirezav** [benglard/waffle#18]

**Comment by benglard** [comment]
for https support I'd recommend using waffle behind a reverse proxy like nginx (I can try to help out a bit if you try this)

**Comment by alirezav** [comment]
I followed steps here (https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins) and looks like it is working. Thanks for the pointer.

**Comment by benglard** [comment]
great to hear!
