### ISSUE TITLE
getting image from a POST

### ISSUE THREAD

**Issue by saurabhRTR** [benglard/waffle#2]
Hi there,

Thanks for this nice library. I am trying to receive images as a REST API. I have one version that works with base64 encoded images like so -

```
app.post('/image/', function(req, res)
   local img = base64.decode(req.body)
   local tmpfile = getname(req.body)
   local tmphandle = assert(io.open(app.datadir .. tmpfile, 'wb'))

   tmphandle:write(img)
   io.close(tmphandle)
   res.json{file_id=tmpfile}
end)
```

But this is too slow.. I'm trying to get another version working with multipart image so it works faster.
I'm using the example shown for multipart forms but I am not able to get it to work with this code -

```
app.post('/m/', function(req, res)
    local tmpfile = getname(req.body)

    print("got file " .. tmpfile ..'!')
    req.form.file:save{path = app.datadir .. tmpfile}
    res.json{file_id = tmpfile}
end)
```

It doesn't seem to work for binary image posts. Have you tried this before?

Thanks,

**Comment by benglard** [comment]
Is the first version too slow even for a single image, or is it only too slow when benchmarked with a large number of open connections? Regardless, you should use non-blocking filesystem IO. That is what the multipart save function is using (https://github.com/benglard/waffle/blob/master/waffle/request.lua#L24), made possible by the underlying async library. For the second version, I'd have to see more code/example form inputs to debug. Thanks for giving the library a try!

**Comment by sanealytics** [comment]
Thanks Ben. I figured it out. It was a combination of updates to async and my lack of understanding lua.

All good..

**Comment by benglard** [comment]
Glad you figured it out. Let me know if I can help again.
