### ISSUE TITLE
loop or previous error loading module 'buffer'

### ISSUE THREAD

**Issue by pefi9** [benglard/waffle#4]
Hi,

when I run "require 'waffle' in torch I get this error:

th> require 'waffle'
...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:383: ...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:383: ...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:383: ...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:383: ...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:383: ...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:383: loop or previous error loading module 'buffer'
stack traceback:
    ...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:500: in function <...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:493>
    [C]: in function 'error'
    ...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
    [string "_RESULT={require 'waffle'}"]:1: in main chunk
    [C]: in function 'xpcall'
    ...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:650: in function 'repl'
    .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
    [C]: ?  
                                                                      [0.0375s] 
th> 

I have OS X, El Capitan.

**Comment by benglard** [comment]
Can you tell me what happens when you run th and require 'buffer'? Thanks

**Comment by pefi9** [comment]
th> require 'buffer'
...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:383: ...petrfiala/torch/install/share/lua/5.1/trepl/init.lua:383: module 'bit' not found:No LuaRocks module found for bit
        no field package.preload['bit']
        no file '/Users/petrfiala/.luarock

So I installed: luarocks install luabitop
and now it's all running ... require 'buffer' and 'waffle'

Thanks

**Comment by benglard** [comment]
Great!
