### ISSUE TITLE
Server hanging when making parallel requests for static content

### ISSUE THREAD

**Issue by etiennem2** [benglard/waffle#5]
We define an entry point for static content like this
app.set('public','/path/ImagesDownSampled/down.3/')

and then we make a few parallel requests with curl (these are images, ranging in size 5k to 10k bytes and the server often (easy to reproduce) hangs on some of the requests. This doesn't seem to happen when we serialize the calls (so far we have not hit an issue). When this error occurs we see "error on client - code: 13".

**Comment by benglard** [comment]
Thanks for pointing this out. I believe I fixed the issue with the latest commit - can you confirm?

**Comment by etiennem2** [comment]
This works nicely. Thanks a lot.

**Comment by benglard** [comment]
Great!

**Comment by etiennem2** [comment]
Updated yesterday, noticed problem behavior returns, when you ask for different resources in parallel the server gets confused and does produce complete/correct responses. Your fix from Feb. 24th was working. Thanks.

**Comment by benglard** [comment]
Sorry about that, please try again with latest commit

**Comment by etiennem2** [comment]
Great, working again. Thanks a lot for the prompt reply.
