### ISSUE TITLE
Allow changing content type for static files

### ISSUE THREAD

**Issue by sanealytics** [benglard/waffle#7]
Hi there,

Thanks for the amazing package. It has really sped up my torch development.

I am trying to serve a specific kind of file and say what it is in the content type. In other words, I want to say for file x.myfile the content type is 'application/myfile'. 

Is the best way to do this to modify the code at https://github.com/benglard/waffle/blob/master/waffle/response.lua#L47 ?

Apologies as I'm new to lua and not quite sure what the best way to do this is.

Thanks,

**Comment by benglard** [comment]
Glad the library has been useful! Update to the latest commit and you'll be able to do this with sendFile: `res.header('Content-Type', 'text/plain')` like you would typically

**Comment by sanealytics** [comment]
thanks! Works like a charm
