### ISSUE TITLE
attempt to call method 'toImage' (a nil value)

### ISSUE THREAD

**Issue by ll36771** [benglard/waffle#8]
when i use local img = req.form.file:toImage() in my project,it turns out attempt to call method 'toImage' (a nil value).I have installed GraphicsMagick and require it.What is the problem?
@benglard

**Comment by benglard** [comment]
What is the value of req.form.file?

**Comment by ll36771** [comment]
Thanks for your reply.Now i put the image data into the body of post.And i use gm to transfer blob to image.

**Comment by benglard** [comment]
Ok glad that works
